// generated by stringer -type DressupKey dressup_key.go; DO NOT EDIT

package goprecure

import "fmt"

const _DressupKey_name = "FloraMermaidTwinkleScarletRoseIceLunaHanabiLilyBubbleShootingStarPhoenixSakuraSangoGingaSunRoyal"

var _DressupKey_index = [...]uint8{0, 5, 12, 19, 26, 30, 33, 37, 43, 47, 53, 65, 72, 78, 83, 88, 91, 96}

func (i DressupKey) String() string {
	if i < 0 || i >= DressupKey(len(_DressupKey_index)-1) {
		return fmt.Sprintf("DressupKey(%d)", i)
	}
	return _DressupKey_name[_DressupKey_index[i]:_DressupKey_index[i+1]]
}
