// generated by stringer -type DressupKey dressup_key.go; DO NOT EDIT

package go_princess_precure

import "fmt"

const _DressupKey_name = "TransformFloraTransformMermaidTransformTwinkleTransformScarlett"

var _DressupKey_index = [...]uint8{0, 14, 30, 46, 63}

func (i DressupKey) String() string {
	if i < 0 || i >= DressupKey(len(_DressupKey_index)-1) {
		return fmt.Sprintf("DressupKey(%d)", i)
	}
	return _DressupKey_name[_DressupKey_index[i]:_DressupKey_index[i+1]]
}
